/*
 * Payment System Rest API
 *
 * Payment System Rest API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type CreateTransactionRequest struct {
	DebitId uint `json:"debit_id"`

	CreditId uint `json:"credit_id"`

	Amount uint `json:"amount"`

	Description string `json:"description,omitempty"`
}
