/*
 * Payment System Rest API
 *
 * Payment System Rest API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type CreateWalletResponse struct {
	Status ResponseStatus `json:"status,omitempty"`

	CreatedWalletId uint `json:"created_wallet_id,omitempty"`
}
