/*
 * Payment System Rest API
 *
 * Payment System Rest API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type CreateWalletRequest struct {
	Name string `json:"name"`

	Description string `json:"description,omitempty"`
}
